version: '3.1'

services:

  typesense:
    image: typesense/typesense:0.25.1
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ${CONFIG_DATA_DIRECTORY}/typesense:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'

  postgres:
    image: ankane/pgvector:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

volumes:
  pgdata:
